name: Build TopSkyMaps

on:
  push:
    branches:
      - main
    paths:
      - '.data/TopSkyMaps/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Concatenate and clean files
      run: |
        python .github/workflows/concatenate_topskymaps.py

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add 'OTDF/Plugins/TopSky/TWR_LeadInSky/TopSkyMaps.txt'
        git add 'OTDF/Plugins/TopSky/LeadInSky/TopSkyMaps.txt'
        git commit -m 'Update TopSkyMaps files'
        git push

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Upload cleaned files
        path: |
          OTDF/Plugins/TopSky/TWR_LeadInSky/TopSkyMaps.txt
          OTDF/Plugins/TopSky/LeadInSky/TopSkyMaps.txt